const fs = require('fs');
const path = require('path');

const baseDir = path.join(__dirname, '..', 'src', 'locales');

// ============ ALL TRANSLATIONS FOR ALL 10 LANGUAGES ============
const t = {};

// Spanish (es)
t.es = {
  productFamily: {
    eyebrow: "La familia BiblioFuse",
    titleA: "Un ecosistema.",
    titleB: "Herramientas para ser dueño de tus archivos.",
    desc: "Creado por Modern Logic Tech Solutions para lectores y coleccionistas que guardan su biblioteca en sus propios dispositivos, no detrás del inicio de sesión de otra persona.",
    alsoOn: "también en",
    products: {
      reader: { tag: "Insignia", desc: "Lector y gestor de biblioteca nativo para colecciones personales de e-books y cómics.", bullet1: "EPUB, PDF, CBZ, CBR, RAR, ZIP y TXT", bullet2: "Etiquetas, valoraciones, progreso y marcadores", bullet3: "Biblioteca iCloud en iPhone, iPad y Mac", cta: "Descargar en App Store", secondary: "Google Play" },
      webTool: { tag: "Gratis", desc: "Convierte, combina y comprime archivos de e-books en tu navegador, sin instalación, totalmente en el dispositivo.", bullet1: "Combinar y convertir EPUB / PDF / CBZ / ZIP", bullet2: "Impulsado por WebAssembly, 100% privado", bullet3: "Funciona en cualquier plataforma con navegador", cta: "Abrir herramienta web" },
      archive: { tag: "Mac · Windows", desc: "Encuentra y elimina archivos duplicados de cómics, fotos y archivos, incluso si han sido renombrados, recomprimidos o guardados en diferentes carpetas.", bullet1: "Hashing perceptual para CBZ/CBR/ZIP/RAR", bullet2: "Selección automática inteligente y eliminación segura a la Papelera", bullet3: "Caché de hash para escaneos rápidos repetidos", cta: "Mac App Store", secondary: "Microsoft Store" },
      smartdecrypt: { tag: "iOS · Mac · Windows", desc: "Desbloquea PDFs y archivos protegidos con contraseña usando patrones de nombres de archivo guardados.", bullet1: "Soporte para PDF, ZIP y 7z", bullet2: "Coincidencia de patrones para archivos recurrentes", bullet3: "Contraseñas guardadas en el Llavero del sistema", cta: "iOS · Mac App Store", secondary: "Microsoft Store" }
    }
  },
  readerSection: {
    eyebrow: "BiblioFuse Reader",
    title: "Diseñado para largas sesiones de lectura.",
    desc: "Un lector enfocado con las herramientas de biblioteca que realmente usas: formatos, carpetas, etiquetas, valoraciones, progreso y marcadores. La misma biblioteca en iPhone, iPad y Mac, sincronizada a través de iCloud.",
    features: {
      library: { eyebrow: "Biblioteca", title: "Un estante para cada formato.", desc: "EPUB, PDF, CBZ, CBR, RAR, ZIP y TXT: lee en una sola biblioteca con carpetas, búsqueda y libros recientes. Importa desde Archivos, selector de documentos o tu iCloud Drive.", bullet1Title: "Etiquetas y valoraciones", bullet1Body: "organiza sin carpetas si lo prefieres.", bullet2Title: "Progreso de lectura", bullet2Body: "cada libro recuerda dónde lo dejaste.", bullet3Title: "iCloud multidispositivo", bullet3Body: "retoma en iPhone donde paraste en iPad.", imageAlt: "Biblioteca BiblioFuse con etiquetas, valoraciones y progreso de lectura" },
      reading: { eyebrow: "Lee a tu manera", title: "TTS, auto-desplazamiento y peek zoom.", desc: "Un lector sin distracciones con los controles que importan para sesiones largas. Texto a voz para EPUB y TXT. Auto-desplazamiento para cómics y webtoons. Peek zoom para inspeccionar un panel sin perder tu lugar.", bullet1Title: "Texto a voz", bullet1Body: "narración manos libres para EPUB y TXT.", bullet2Title: "Auto-desplazamiento", bullet2Body: "paginado o continuo, ajustado para archivos de imagen.", bullet3Title: "Peek zoom", bullet3Body: "doble toque para inspeccionar paneles densos y texto pequeño.", imageAlt: "Vista de lectura BiblioFuse con TTS, auto-scroll y peek zoom" },
      streaming: { eyebrow: "Mac transmite al móvil", title: "Central de biblioteca. Transmite a tu iPhone.", badge: "Sin servidor externo · Sin suscripción", desc: "En Mac, BiblioFuse se convierte en una central de biblioteca de escritorio: gestiona carpetas locales, carpetas iCloud y recursos compartidos de red SMB en una interfaz dividida de biblioteca/lector. Luego transmite libros directamente a BiblioFuse en iPhone y iPad por Wi-Fi local en casa, o remotamente por 5G cuando estás fuera.", bullet1Title: "Streaming Wi-Fi local", bullet1Body: "navegación instantánea desde cualquier fuente Mac.", bullet2Title: "Streaming remoto 5G", bullet2Body: "abre tu biblioteca desde cualquier lugar con Tailscale.", bullet3Title: "Fuentes locales, iCloud y SMB", bullet3Body: "una biblioteca Mac, todas las carpetas que ya tienes.", bullet4Title: "PIN opcional", bullet4Body: "bloquea el acceso de streaming en redes compartidas.", imageAlt: "Biblioteca Mac BiblioFuse con lector de vista dividida", footnote: "El acceso remoto requiere iCloud iniciado y Tailscale conectado tanto en Mac como en iOS. También recomendamos usar Tailscale para conexiones Wi-Fi locales seleccionando el nombre del dispositivo con \"(iCloud)\"." }
    }
  },
  toolsHighlight: { badge: "Herramientas integradas", title: "Comprime y combina sin salir de la app.", supports: "Compatible con", onDevice: "Todo el procesamiento se ejecuta en el dispositivo. Nada se sube.", tools: { resize: { title: "Redimensionar al lado más corto", body: "Establece una dimensión mínima objetivo y repagina cada imagen de tu archivo.", kpi: "1080 px", label: "Preajuste típico" }, convert: { title: "Convertir a WebP o JPG", body: "Recodifica páginas a WebP o JPG para archivos más pequeños que aún se ven nítidos.", kpi: "Hasta 50%", label: "Archivos más pequeños" }, merge: { title: "Combinar capítulos y series", body: "Combina capítulos, volúmenes o descargas divididas en un solo CBZ, ZIP o PDF limpio.", kpi: "Muchos a 1", label: "Una pasada" } } },
  archiveSection: { badge: "App hermana · Mac y Windows", titleA: "Encuentra archivos duplicados.", titleB: "Incluso después de renombrar.", desc: "Archive Duplicate Scanner encuentra y elimina archivos duplicados de cómics, fotos y archivos, incluso cuando han sido renombrados, recomprimidos o guardados en diferentes carpetas.", features: { scanning: { title: "Escaneo de archivos de cómics", body: "CBZ, CBR, ZIP y RAR usando hash perceptual." }, photo: { title: "Detección de fotos duplicadas", body: "JPG, PNG, HEIC, WEBP, BMP y GIF." }, select: { title: "Selección automática inteligente", body: "Conservar el más grande, más pequeño, más nuevo, más antiguo o con más páginas." }, delete: { title: "Eliminación segura", body: "Los archivos marcados solo se mueven a la Papelera del sistema." } }, altBadge: "Descargar Archive Duplicate Scanner en la Mac App Store", altImage: "Archive Duplicate Scanner configurar e iniciar escaneo", pricing: "El uso gratuito está disponible para siempre para escaneos de hasta 1,000 archivos. Una prueba de 7 días desbloquea el acceso completo, y una compra única desbloquea el uso ilimitado sin suscripción.", stats: { threshold: "Umbral predeterminado", sampled: "Páginas muestreadas", local: "100% local", noCloud: "Sin nube, sin rastreo" } },
  decryptSection: { badge: "App hermana · iOS · Mac · Windows", titleA: "Suelta el archivo.", titleB: "Se desbloquea solo.", desc: "SmartDecrypt te ayuda a desbloquear PDFs y archivos protegidos con contraseña sin buscar entre notas, mensajes o correos antiguos la contraseña correcta.", features: { formats: { title: "PDF · ZIP · 7z", body: "Desbloquea PDFs protegidos y extrae archivos ZIP/7z." }, patterns: { title: "Patrones guardados", body: "Coincide automáticamente con formatos de nombres de archivo recurrentes." }, batch: { title: "Actualización por lotes", body: "Pro de pago único desbloquea carga por lotes y ciclo de contraseñas." }, keychain: { title: "Seguro en el Llavero", body: "Las contraseñas permanecen en el Llavero de Apple." } }, altBadge: "Descargar SmartDecrypt PDF ZIP en la App Store", pricing: "Los usuarios gratuitos pueden desbloquear un archivo a la vez con coincidencia de patrones. SmartDecrypt Pro es una compra universal única que desbloquea la carga de archivos por lotes y el ciclo automático de contraseñas en iOS y macOS.", steps: { drop: "Soltar archivos", match: "Coincidir patrón", unlock: "Desbloqueado" }, queueTitle: "Cola (3)", queueStatus: "Coincidencia automática activa", states: { unlocked: "desbloqueado", matching: "coincidiendo", queued: "en cola" } },
  privacyStrip: { eyebrow: "Por qué BiblioFuse", title: "Construido sobre unos pocos principios simples.", items: { noAds: { title: "Sin anuncios", body: "Disfruta de lectura ininterrumpida sin publicidad." }, noTracking: { title: "Sin rastreo", body: "No recopilamos ni vendemos tus datos de lectura." }, cloudSync: { title: "Sincronización en la nube", body: "Sincroniza tu biblioteca entre dispositivos Apple con iCloud." }, compression: { title: "Compresión inteligente", body: "Reduce el tamaño de archivo y ahorra espacio sin salir de la app." } } },
  finalCta: { badge: "Empieza aquí", title: "Tu biblioteca. Tu dispositivo. Tus reglas.", desc: "Empieza con el Reader. Añade las utilidades cuando las necesites. Todo permanece en el dispositivo.", button: "Probar la herramienta web" },
  stickyBar: { text: "Obtener BiblioFuse" },
  altTexts: { heroImage: "Biblioteca BiblioFuse en iPhone", logo: "Logotipo de BiblioFuse", appStore: "Descargar en la App Store", googlePlay: "Descargar en Google Play", microsoftStore: "Descargar de Microsoft" }
};

// French (fr)
t.fr = {
  productFamily: {
    eyebrow: "La famille BiblioFuse",
    titleA: "Un écosystème.",
    titleB: "Des outils pour posséder vos fichiers.",
    desc: "Créé par Modern Logic Tech Solutions pour les lecteurs et collectionneurs qui gardent leur bibliothèque sur leurs propres appareils, pas derrière le login de quelqu'un d'autre.",
    alsoOn: "aussi sur",
    products: {
      reader: { tag: "Phare", desc: "Lecteur et gestionnaire de bibliothèque natif pour collections personnelles d'ebooks et de BD.", bullet1: "EPUB, PDF, CBZ, CBR, RAR, ZIP et TXT", bullet2: "Étiquettes, notes, progression et marque-pages", bullet3: "Bibliothèque iCloud sur iPhone, iPad et Mac", cta: "Télécharger sur l'App Store", secondary: "Google Play" },
      webTool: { tag: "Gratuit", desc: "Convertissez, fusionnez et compressez vos e-books dans le navigateur, sans installation, entièrement sur l'appareil.", bullet1: "Fusion et conversion EPUB / PDF / CBZ / ZIP", bullet2: "Propulsé par WebAssembly, 100% privé", bullet3: "Fonctionne sur toute plateforme avec un navigateur", cta: "Lancer l'outil web" },
      archive: { tag: "Mac · Windows", desc: "Trouve et supprime les archives de BD, photos et fichiers en double, même après renommage, recompression ou déplacement.", bullet1: "Hachage perceptuel pour CBZ/CBR/ZIP/RAR", bullet2: "Sélection automatique intelligente et suppression sécurisée vers la Corbeille", bullet3: "Cache de hachage pour analyses rapides répétées", cta: "Mac App Store", secondary: "Microsoft Store" },
      smartdecrypt: { tag: "iOS · Mac · Windows", desc: "Déverrouille les PDF et archives protégés par mot de passe grâce à des motifs de noms de fichiers enregistrés.", bullet1: "Prise en charge PDF, ZIP et 7z", bullet2: "Correspondance de motifs pour fichiers récurrents", bullet3: "Mots de passe stockés dans le Trousseau système", cta: "iOS · Mac App Store", secondary: "Microsoft Store" }
    }
  },
  readerSection: {
    eyebrow: "BiblioFuse Reader",
    title: "Conçu pour les longues sessions de lecture.",
    desc: "Un lecteur concentré avec les outils de bibliothèque que vous utilisez vraiment : formats, dossiers, étiquettes, notes, progression et marque-pages. La même bibliothèque sur iPhone, iPad et Mac, synchronisée via iCloud.",
    features: {
      library: { eyebrow: "Bibliothèque", title: "Une étagère pour chaque format.", desc: "EPUB, PDF, CBZ, CBR, RAR, ZIP et TXT : lisez dans une seule bibliothèque avec dossiers, recherche et livres récents. Importez depuis Fichiers, le sélecteur de documents ou votre iCloud Drive.", bullet1Title: "Étiquettes et notes", bullet1Body: "organisez sans dossiers si vous préférez.", bullet2Title: "Progression de lecture", bullet2Body: "chaque livre se souvient où vous vous êtes arrêté.", bullet3Title: "iCloud multi-appareils", bullet3Body: "reprenez sur iPhone là où vous avez arrêté sur iPad.", imageAlt: "Bibliothèque BiblioFuse avec étiquettes, notes et progression" },
      reading: { eyebrow: "Lisez à votre façon", title: "TTS, défilement auto et peek zoom.", desc: "Un lecteur sans distraction avec les commandes qui comptent pour les longues sessions. Synthèse vocale pour EPUB et TXT. Défilement automatique pour BD et webtoons. Peek zoom pour inspecter une case sans perdre votre place.", bullet1Title: "Synthèse vocale", bullet1Body: "narration mains libres pour EPUB et TXT.", bullet2Title: "Défilement automatique", bullet2Body: "paginé ou continu, optimisé pour les archives d'images.", bullet3Title: "Peek zoom", bullet3Body: "double-tap pour inspecter les cases denses et les petits textes.", imageAlt: "Vue de lecture BiblioFuse avec TTS, défilement auto et peek zoom" },
      streaming: { eyebrow: "Le Mac diffuse vers le mobile", title: "Hub de bibliothèque. Diffusez vers votre iPhone.", badge: "Aucun serveur tiers · Aucun abonnement", desc: "Sur Mac, BiblioFuse devient un hub de bibliothèque de bureau : gérez les dossiers locaux, les dossiers iCloud et les partages réseau SMB dans une interface divisée bibliothèque/lecteur. Diffusez ensuite les livres directement vers BiblioFuse sur iPhone et iPad via le Wi-Fi local à la maison, ou à distance en 5G lorsque vous êtes dehors.", bullet1Title: "Diffusion Wi-Fi locale", bullet1Body: "navigation instantanée depuis n'importe quelle source Mac.", bullet2Title: "Diffusion 5G à distance", bullet2Body: "ouvrez votre bibliothèque depuis n'importe où avec Tailscale.", bullet3Title: "Sources locales, iCloud et SMB", bullet3Body: "une bibliothèque Mac, tous les dossiers que vous avez déjà.", bullet4Title: "PIN optionnel", bullet4Body: "verrouillez l'accès en streaming sur les réseaux partagés.", imageAlt: "Bibliothèque Mac BiblioFuse avec lecteur en vue divisée", footnote: "L’accès à distance nécessite une connexion iCloud et Tailscale sur Mac et iOS. Nous recommandons aussi d’utiliser Tailscale pour les connexions Wi-Fi locales en sélectionnant le nom de l’appareil avec « (iCloud) »." }
    }
  },
  toolsHighlight: { badge: "Outils intégrés", title: "Compressez et fusionnez sans quitter l'application.", supports: "Prend en charge", onDevice: "Tout le traitement s'exécute sur l'appareil. Rien n'est téléchargé.", tools: { resize: { title: "Redimensionner au côté le plus court", body: "Définissez une dimension cible et repaginez chaque image de votre archive.", kpi: "1080 px", label: "Préréglage typique" }, convert: { title: "Convertir en WebP ou JPG", body: "Réencodez les pages en WebP ou JPG pour des archives plus petites et nettes.", kpi: "Jusqu'à 50%", label: "Fichiers plus petits" }, merge: { title: "Fusionner chapitres et séries", body: "Combinez chapitres, volumes ou téléchargements fractionnés en un seul CBZ, ZIP ou PDF propre.", kpi: "Plusieurs en 1", label: "En une passe" } } },
  archiveSection: { badge: "App sœur · Mac et Windows", titleA: "Trouvez les archives en double.", titleB: "Même après renommage.", desc: "Archive Duplicate Scanner trouve et supprime les archives de BD, photos et fichiers en double, même après renommage, recompression ou déplacement dans différents dossiers.", features: { scanning: { title: "Analyse d'archives de BD", body: "CBZ, CBR, ZIP et RAR par hachage perceptuel." }, photo: { title: "Détection de photos en double", body: "JPG, PNG, HEIC, WEBP, BMP et GIF." }, select: { title: "Sélection automatique intelligente", body: "Gardez le plus grand, le plus petit, le plus récent, le plus ancien ou le plus de pages." }, delete: { title: "Suppression sécurisée", body: "Les fichiers marqués ne sont déplacés que vers la Corbeille système." } }, altBadge: "Télécharger Archive Duplicate Scanner sur le Mac App Store", altImage: "Archive Duplicate Scanner configurer et lancer l'analyse", pricing: "L'utilisation gratuite est disponible pour toujours pour les analyses jusqu'à 1 000 fichiers. Un essai de 7 jours débloque l'accès complet, et un achat unique débloque une utilisation illimitée sans abonnement.", stats: { threshold: "Seuil par défaut", sampled: "Pages échantillonnées", local: "100% local", noCloud: "Sans cloud, sans pistage" } },
  decryptSection: { badge: "App sœur · iOS · Mac · Windows", titleA: "Déposez le fichier.", titleB: "Il se déverrouille tout seul.", desc: "SmartDecrypt vous aide à déverrouiller les PDF et archives protégés par mot de passe sans chercher dans vos notes, messages ou anciens emails le bon mot de passe.", features: { formats: { title: "PDF · ZIP · 7z", body: "Déverrouillez les PDF protégés et extrayez les archives ZIP/7z." }, patterns: { title: "Motifs enregistrés", body: "Faites correspondre automatiquement les formats de noms de fichiers récurrents." }, batch: { title: "Mise à niveau par lots", body: "La version Pro en achat unique débloque le chargement par lots et le cycle des mots de passe." }, keychain: { title: "Sécurisé dans le Trousseau", body: "Les mots de passe restent dans le Trousseau Apple." } }, altBadge: "Télécharger SmartDecrypt PDF ZIP sur l'App Store", pricing: "Les utilisateurs gratuits peuvent déverrouiller un fichier à la fois avec correspondance de motifs. SmartDecrypt Pro est un achat universel unique qui débloque le chargement de fichiers par lots et le cycle automatique des mots de passe sur iOS et macOS.", steps: { drop: "Déposer les fichiers", match: "Faire correspondre", unlock: "Déverrouillé" }, queueTitle: "File d'attente (3)", queueStatus: "Correspondance automatique active", states: { unlocked: "déverrouillé", matching: "en correspondance", queued: "en attente" } },
  privacyStrip: { eyebrow: "Pourquoi BiblioFuse", title: "Construit sur quelques principes simples.", items: { noAds: { title: "Sans publicité", body: "Profitez d'une lecture ininterrompue sans publicités." }, noTracking: { title: "Sans pistage", body: "Nous ne collectons ni ne vendons vos données de lecture." }, cloudSync: { title: "Synchro cloud", body: "Synchronisez votre bibliothèque entre appareils Apple avec iCloud." }, compression: { title: "Compression intelligente", body: "Réduisez la taille des fichiers et économisez de l'espace sans quitter l'application." } } },
  finalCta: { badge: "Commencez ici", title: "Votre bibliothèque. Votre appareil. Vos règles.", desc: "Commencez avec le Reader. Ajoutez les utilitaires quand vous en avez besoin. Tout reste sur l'appareil.", button: "Essayer l'outil web" },
  stickyBar: { text: "Obtenir BiblioFuse" },
  altTexts: { heroImage: "Bibliothèque BiblioFuse sur iPhone", logo: "Logo BiblioFuse", appStore: "Télécharger sur l'App Store", googlePlay: "Télécharger sur Google Play", microsoftStore: "Télécharger depuis Microsoft" }
};

// Continue with more languages... this file is getting very long.
// Let me write the rest of the translations inline.

// Dutch (nl)
t.nl = {
  productFamily: {
    eyebrow: "De BiblioFuse-familie",
    titleA: "Eén ecosysteem.",
    titleB: "Tools om je bestanden te bezitten.",
    desc: "Gebouwd door Modern Logic Tech Solutions voor lezers en verzamelaars die hun bibliotheek op hun eigen apparaten houden, niet achter andermans login.",
    alsoOn: "ook op",
    products: {
      reader: { tag: "Vlaggenschip", desc: "Native lezer en bibliotheekbeheerder voor persoonlijke e-book- en stripcollecties.", bullet1: "EPUB, PDF, CBZ, CBR, RAR, ZIP en TXT", bullet2: "Tags, beoordelingen, voortgang en bladwijzers", bullet3: "iCloud-bibliotheek op iPhone, iPad en Mac", cta: "Download in App Store", secondary: "Google Play" },
      webTool: { tag: "Gratis", desc: "Converteer, voeg samen en comprimeer e-bookbestanden in je browser, geen installatie, volledig op het apparaat.", bullet1: "EPUB / PDF / CBZ / ZIP samenvoegen en converteren", bullet2: "Aangedreven door WebAssembly, 100% privé", bullet3: "Werkt op elk platform met een browser", cta: "Start webtool" },
      archive: { tag: "Mac · Windows", desc: "Vindt en verwijdert dubbele striparchieven, foto's en bestanden, zelfs na hernoemen, hercomprimeren of opslaan in andere mappen.", bullet1: "Perceptuele hashing voor CBZ/CBR/ZIP/RAR", bullet2: "Slimme autoselectie en veilig verwijderen naar prullenbak", bullet3: "Hash-cache voor snelle herhaalscans", cta: "Mac App Store", secondary: "Microsoft Store" },
      smartdecrypt: { tag: "iOS · Mac · Windows", desc: "Ontgrendelt met wachtwoord beveiligde PDF's en archieven met opgeslagen bestandsnaampatronen.", bullet1: "Ondersteuning voor PDF, ZIP en 7z", bullet2: "Patroonherkenning voor terugkerende bestanden", bullet3: "Wachtwoorden opgeslagen in systeemsleutelhanger", cta: "iOS · Mac App Store", secondary: "Microsoft Store" }
    }
  },
  readerSection: {
    eyebrow: "BiblioFuse Reader",
    title: "Gebouwd voor lange leessessies.",
    desc: "Een gefocuste lezer met de bibliotheektools die je echt gebruikt: formaten, mappen, tags, beoordelingen, voortgang en bladwijzers. Dezelfde bibliotheek op iPhone, iPad en Mac, gesynchroniseerd via iCloud.",
    features: {
      library: { eyebrow: "Bibliotheek", title: "Eén plank voor elk formaat.", desc: "EPUB, PDF, CBZ, CBR, RAR, ZIP en TXT: lees in één bibliotheek met mappen, zoekopdracht en recente boeken. Importeer vanuit Bestanden, documentkiezer of je iCloud Drive.", bullet1Title: "Tags en beoordelingen", bullet1Body: "organiseer zonder mappen als je dat wilt.", bullet2Title: "Leesvoortgang", bullet2Body: "elk boek onthoudt waar je was gebleven.", bullet3Title: "iCloud cross-device", bullet3Body: "ga verder op iPhone waar je stopte op iPad.", imageAlt: "BiblioFuse-bibliotheek met tags, beoordelingen en leesvoortgang" },
      reading: { eyebrow: "Lees op jouw manier", title: "TTS, auto-scroll en peek zoom.", desc: "Een afleidingsvrije lezer met de bediening die telt voor lange sessies. Tekst-naar-spraak voor EPUB en TXT. Auto-scroll voor strips en webtoons. Peek zoom om een paneel te inspecteren zonder je plaats te verliezen.", bullet1Title: "Tekst-naar-spraak", bullet1Body: "handsfree vertelling voor EPUB en TXT.", bullet2Title: "Auto-scroll", bullet2Body: "gepagineerd of doorlopend, afgestemd op beeldarchieven.", bullet3Title: "Peek zoom", bullet3Body: "dubbeltik om dichte panelen en kleine tekst te inspecteren.", imageAlt: "BiblioFuse leesweergave met TTS, auto-scroll en peek zoom" },
      streaming: { eyebrow: "Mac streamt naar mobiel", title: "Bibliotheekhub. Stream naar je iPhone.", badge: "Geen server van derden · Geen abonnement", desc: "Op Mac wordt BiblioFuse een desktopbibliotheekhub: beheer lokale mappen, iCloud-mappen en SMB-netwerkshares in een split-view bibliotheek/lezer-interface. Stream boeken rechtstreeks naar BiblioFuse op iPhone en iPad via lokale Wi-Fi thuis, of op afstand via 5G als je onderweg bent.", bullet1Title: "Lokale Wi-Fi-streaming", bullet1Body: "direct bladeren vanaf elke Mac-bron.", bullet2Title: "Externe 5G-streaming", bullet2Body: "open je thuisbibliotheek overal met Tailscale.", bullet3Title: "Lokale, iCloud- en SMB-bronnen", bullet3Body: "één Mac-bibliotheek, elke map die je al hebt.", bullet4Title: "Optionele pincode", bullet4Body: "vergrendel streamingtoegang op gedeelde netwerken.", imageAlt: "BiblioFuse Mac-bibliotheek met split-view lezer", footnote: "Toegang op afstand vereist dat iCloud is aangemeld en Tailscale is verbonden op zowel Mac als iOS. We raden ook aan Tailscale te gebruiken voor lokale Wi-Fi-verbindingen door de apparaatnaam met \"(iCloud)\" te kiezen." }
    }
  },
  toolsHighlight: { badge: "Ingebouwde tools", title: "Comprimeren en samenvoegen zonder de app te verlaten.", supports: "Ondersteunt", onDevice: "Alle verwerking vindt plaats op het apparaat. Niets wordt geüpload.", tools: { resize: { title: "Formaat wijzigen naar kortste zijde", body: "Stel een doeldimensie in en herpagineer elke afbeelding in je archief.", kpi: "1080 px", label: "Standaard voorinstelling" }, convert: { title: "Converteren naar WebP of JPG", body: "Hercodeer pagina's naar WebP of JPG voor kleinere archieven die er nog scherp uitzien.", kpi: "Tot 50%", label: "Kleinere bestanden" }, merge: { title: "Hoofdstukken en series samenvoegen", body: "Combineer hoofdstukken, volumes of gesplitste downloads tot één schoon CBZ-, ZIP- of PDF-bestand.", kpi: "Veel naar 1", label: "In één keer" } } },
  archiveSection: { badge: "Zusterapp · Mac en Windows", titleA: "Vind dubbele archieven.", titleB: "Zelfs na hernoemen.", desc: "Archive Duplicate Scanner vindt en verwijdert dubbele striparchieven, foto's en bestanden, zelfs na hernoemen, hercomprimeren of opslaan in andere mappen.", features: { scanning: { title: "Striparchiefscanning", body: "CBZ, CBR, ZIP en RAR met perceptuele hashing." }, photo: { title: "Fotoduplicaatdetectie", body: "JPG, PNG, HEIC, WEBP, BMP en GIF." }, select: { title: "Slimme autoselectie", body: "Behoud grootste, kleinste, nieuwste, oudste of meeste pagina's." }, delete: { title: "Veilig verwijderen", body: "Gemarkeerde bestanden worden alleen naar de systeemprullenbak verplaatst." } }, altBadge: "Download Archive Duplicate Scanner in de Mac App Store", altImage: "Archive Duplicate Scanner configureren en scan starten", pricing: "Gratis gebruik is voor altijd beschikbaar voor scans tot 1.000 bestanden. Een proefperiode van 7 dagen ontgrendelt volledige toegang, en een eenmalige aankoop ontgrendelt onbeperkt gebruik zonder abonnement.", stats: { threshold: "Standaarddrempel", sampled: "Bemonsterde pagina's", local: "100% lokaal", noCloud: "Geen cloud, geen tracking" } },
  decryptSection: { badge: "Zusterapp · iOS · Mac · Windows", titleA: "Laat het bestand vallen.", titleB: "Het ontgrendelt zichzelf.", desc: "SmartDecrypt helpt je met wachtwoord beveiligde PDF's en archieven te ontgrendelen zonder te zoeken in notities, berichten of oude e-mails naar het juiste wachtwoord.", features: { formats: { title: "PDF · ZIP · 7z", body: "Ontgrendel beveiligde PDF's en pak ZIP/7z-archieven uit." }, patterns: { title: "Opgeslagen patronen", body: "Kom automatisch overeen met terugkerende bestandsnaamformaten." }, batch: { title: "Batch-upgrade", body: "Eenmalige Pro-aankoop ontgrendelt batch-laden en wachtwoordcyclus." }, keychain: { title: "Sleutelhanger-veilig", body: "Wachtwoorden blijven in de Apple-sleutelhanger." } }, altBadge: "Download SmartDecrypt PDF ZIP in de App Store", pricing: "Gratis gebruikers kunnen één bestand tegelijk ontgrendelen met patroonherkenning. SmartDecrypt Pro is een eenmalige universele aankoop die batchbestandslading en automatische wachtwoordcyclus op iOS en macOS ontgrendelt.", steps: { drop: "Bestanden neerzetten", match: "Patroon matchen", unlock: "Ontgrendeld" }, queueTitle: "Wachtrij (3)", queueStatus: "Automatisch matchen actief", states: { unlocked: "ontgrendeld", matching: "matchend", queued: "in wachtrij" } },
  privacyStrip: { eyebrow: "Waarom BiblioFuse", title: "Gebouwd op een paar eenvoudige principes.", items: { noAds: { title: "Geen advertenties", body: "Geniet van ononderbroken lezen zonder advertenties." }, noTracking: { title: "Geen tracking", body: "We verzamelen of verkopen je leesgegevens niet." }, cloudSync: { title: "Cloudsync", body: "Synchroniseer je bibliotheek tussen Apple-apparaten met iCloud." }, compression: { title: "Slimme compressie", body: "Verklein bestandsgrootte en bespaar ruimte zonder de app te verlaten." } } },
  finalCta: { badge: "Begin hier", title: "Jouw bibliotheek. Jouw apparaat. Jouw regels.", desc: "Begin met de Reader. Voeg de hulpprogramma's toe wanneer je ze nodig hebt. Alles blijft op het apparaat.", button: "Probeer de webtool" },
  stickyBar: { text: "Download BiblioFuse" },
  altTexts: { heroImage: "BiblioFuse-bibliotheek op iPhone", logo: "BiblioFuse-logo", appStore: "Download in de App Store", googlePlay: "Download op Google Play", microsoftStore: "Download bij Microsoft" }
};

console.log('Translations for es, fr, nl ready. To be continued...');
console.log('This file is already very large. Let me write the remaining languages in-place.');
